replicaCount: 1

image:
  repository: quang1709/data-processing-job
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30007

resources:
  limits:
    cpu: "400m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
    
serviceAccount:
  create: true
  name: "data-processing-job-sa"