replicaCount: 1

image:
  repository: quang1709/data-processing-job
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30007

resources:
  limits:
    cpu: "400m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: data-processing-job.quang1709.ddns.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: data-processing-job-tls
      hosts:
        - data-processing-job.quang1709.ddns.net